AWSTemplateFormatVersion: 2010-09-09
Description: Resources template for NHL Data Pipeline

Parameters:

  ProjectName:
    Type: String
    Description: Project name

  ImageTag:
    Type: String
    Description: Image tag

Resources:

  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}-data

  ProducerLambdaECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${ProjectName}

  ProducerLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-producer-lambda-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt DataBucket.Arn
                  - !Sub ${DataBucket.Arn}/*

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-lambda
      PackageType: Image
      Role: !GetAtt ProducerLambdaExecutionRole.Arn
      Code:
        ImageUri: !Sub ${ProducerLambdaECRRepository.RepositoryUri}:${ImageTag}
      Timeout: 60 # 1 minute

  ProducerLambdaScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(1 hour)
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: "ProducerLambdaTarget"

  ProducerLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ProducerLambdaScheduledRule.Arn
