AWSTemplateFormatVersion: 2010-09-09
Description: Resources template for NHL Data Pipeline

Parameters:

  ProjectName:
    Type: String
    Description: Project name

  ImageTag:
    Type: String
    Description: Image tag

Resources:

  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}-data

  ProducerLambdaECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${ProjectName}

  # IAM Role for S3 Lambda
  S3LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-s3-lambda-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt DataBucket.Arn
                  - !Sub ${DataBucket.Arn}/*

  # IAM Role for Supabase Lambda
  SupabaseLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-supabase-lambda-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ParameterStoreAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ProjectName}/supabase/*

  # Lambda 1: S3 Upload
  S3LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-s3-lambda
      PackageType: Image
      Role: !GetAtt S3LambdaExecutionRole.Arn
      Code:
        ImageUri: !Sub ${ProducerLambdaECRRepository.RepositoryUri}:${ImageTag}
      ImageConfig:
        Command:
          - nhl_api_s3.lambda_handler
      Environment:
        Variables:
          S3_BUCKET: !Ref DataBucket
      Timeout: 60

  # Lambda 2: Supabase Upload
  SupabaseLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-supabase-lambda
      PackageType: Image
      Role: !GetAtt SupabaseLambdaExecutionRole.Arn
      Code:
        ImageUri: !Sub ${ProducerLambdaECRRepository.RepositoryUri}:${ImageTag}
      ImageConfig:
        Command:
          - nhl_api_supabase.lambda_handler
      Environment:
        Variables:
          SUPABASE_PARAM_PREFIX: !Sub /${ProjectName}/supabase
      Timeout: 60

  # Schedule for S3 Lambda (8 AM EST / 1 PM UTC)
  S3LambdaScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 13 * * ? *)
      Targets:
        - Arn: !GetAtt S3LambdaFunction.Arn
          Id: "S3LambdaTarget"

  S3LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref S3LambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt S3LambdaScheduledRule.Arn

  # Schedule for Supabase Lambda (8 AM EST / 1 PM UTC)
  SupabaseLambdaScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 13 * * ? *)
      Targets:
        - Arn: !GetAtt SupabaseLambdaFunction.Arn
          Id: "SupabaseLambdaTarget"

  SupabaseLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SupabaseLambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt SupabaseLambdaScheduledRule.Arn
