version: 2

sources:
  - name: raw_api_data
    description: "Raw data from Supabase PostgreSQL database"
    schema: public
    tables:
      - name: game_data
        description: "Raw NHL game data ingested from the NHL API. This is sent via a lambda function via a post request to the supabase database."
        columns:
          - name: game_id
            description: "Unique identifier for each NHL game"
          - name: partition_date
            description: "Date of the game"
          - name: event
            description: "Raw NHL game data ingested from the NHL API"

